### ISSUE TITLE
fix: emit production JSX runtime in web component artifacts

### ISSUE THREAD

**Issue by artiphishle** [ankhorage/zora#450]
## Problem

The web-only TreeView artifact introduced by #448 is currently bundled with React's development JSX runtime. A real Next.js production consumer (artiphishle/pkgviz#190) compiles the artifact but fails while prerendering with:

```text
TypeError: jsxDEV is not a function
.generated/zora/tree-view/TreeView.js
```

The artifact is a published production boundary and must not emit `jsxDEV` or import `react/jsx-dev-runtime`.

## Fix

- configure the Bun web-component build explicitly with production automatic JSX;
- keep React external;
- fail the ZORA build if the emitted browser artifact contains `jsxDEV` or `react/jsx-dev-runtime`;
- release as a patch so PKGViz can consume the corrected exact version.

## Acceptance

- [ ] TreeView web artifact imports/uses the production JSX runtime.
- [ ] Build rejects development JSX output.
- [ ] Existing ZORA CI and Expo candidate remain green.
- [ ] Patch changeset is included.

## Consumer

After release, update artiphishle/pkgviz#190 from ZORA 20.1.0 to the corrected patch release.

## Skills to load

- `.agents/skills/ankhorage-coding-rules/SKILL.md`
- `.agents/skills/ankhorage-project-structure/SKILL.md`
- `.agents/skills/hexagonal-architecture/SKILL.md`
